### ISSUE TITLE
Peer to Peer Code Review.

### ISSUE THREAD

**Issue by abdulrahmanshr75** [omarsalem7/My-leaderboard#6]

**Comment by abdulrahmanshr75** [comment]
Hello @omarsalem7. 😄 
Excellent job building the project ✔️ 
Nice code structure ✔️ 
but I suggest that in the readme getting started you add every command in one line.
Perfect work overall 🔥

**Comment by Kandy-Peter** [comment]
Hello @omarsalem7,

You did a nice job and your code is short and well structured but I would to suggest you some changes to make it DRY(don't repeat yourself):
These lines are repeated two times, so what if you create a global variable for it, the way to make it clear and avoid repeating yourself: 

1.  https://github.com/omarsalem7/My-leaderboard/blob/e33fdb3b672a2f9e6addfdabba4df7932894a593/src/index.js#L6
2. https://github.com/omarsalem7/My-leaderboard/blob/e33fdb3b672a2f9e6addfdabba4df7932894a593/src/index.js#L11

And the both also:

3. https://github.com/omarsalem7/My-leaderboard/blob/e33fdb3b672a2f9e6addfdabba4df7932894a593/src/modules/api.js#L4
4.  https://github.com/omarsalem7/My-leaderboard/blob/e33fdb3b672a2f9e6addfdabba4df7932894a593/src/modules/api.js#L12

Happy coding 🥂
